- index.html
- src/App.tsx
- src/pages/home/config/apps.config.tsx
- src/pages/home/home.tsx
- src/pages/home/styles.ts
The Home is created, where by default the `<Header />` and `<Nav />` of Inube are rendered.
> Implement the `Header` and `Nav` of the design system in `Home`

- package-lock.json
- package.json
install dependencies needed to deploy to github pages.
> Add gh-pages and its dependencies

- package-lock.json
- package.json
adjust dependencies and script
> ids deployed at inubeds.vercel.app

- package.json
- tsconfig.json
update the scripts of the dependencies to generate the distributable
> update build and target settings in package.json

- src/components/feedback/cards-components/index.tsx
- src/pages/components/avatar/index.tsx
- src/pages/home/home.tsx
- src/routes/informationComponent.tsx
The example pages and code for the documentation of the `<Avatar/ >` component are implemented.
> implement path to display the example page and code via `<Tabs />`.

- src/pages/home/home.tsx
Validate the operation of the routes from the address bar in the project when it is deployed, since when entering directly an error occurs
> update DetailsSection in Home component

- src/components/data/InformationProps/index.tsx
- src/components/data/InformationProps/styles.ts
- src/design-system/data/Icon/code/index.tsx
- src/design-system/data/Icon/code/parameters.ts
- src/pages/components/icon/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
- vercel.json
add `<Icon />` props documentation
> add content to code tabs for `<Icon />`

- src/design-system/inputs/Button/code/index.tsx
- src/design-system/inputs/Button/code/parameters.ts
- src/pages/components/Button/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Implement the **Code section** for the documentation of the `<Button />` component.
> Add `<Button />` component and its code

- src/components/data/InformationProps/index.tsx
- src/design-system/data/Avatar/code/index.tsx
- src/design-system/inputs/Button/code/parameters.ts
- src/design-system/inputs/Label/code/index.tsx
- src/design-system/inputs/Label/code/parameters.ts
- src/pages/components/Label/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
implementing the code page for the `<Label/ >` component, **documenting** each of the component's props
>  implement the code page for `<Label />`

- src/design-system/inputs/Switch/index.tsx
- src/design-system/inputs/Switch/parameters.ts
- src/pages/components/Switch/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Implement the code page for the `<Switch/ >` component, documenting each of the component props
> Implement the code page for `<Switch />`

- src/design-system/inputs/Textarea/code/index.tsx
- src/design-system/inputs/Textarea/code/parameters.ts
- src/pages/components/data/avatar/index.tsx
- src/pages/components/data/icon/index.tsx
- src/pages/components/inputs/Button/index.tsx
- src/pages/components/inputs/Label/index.tsx
- src/pages/components/inputs/Switch/index.tsx
- src/pages/components/inputs/Textarea/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
implement the code page for the `<Textarea/ >` component, documenting each of the component props
> Add content to code tabs for `<Textarea/ >`

- src/design-system/inputs/Textfield/code/index.tsx
- src/design-system/inputs/Textfield/code/parameters.ts
- src/pages/components/inputs/Textfield/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
implement the code page for the `<Textfield/ >` component, documenting each of the component props
> Add Textarea component and its code in `<Textfield />`

- src/design-system/inputs/Select/code/index.tsx
- src/design-system/inputs/Select/code/parameters.ts
- src/design-system/inputs/Textfield/code/parameters.ts
- src/pages/components/inputs/Select/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Implement the code page for the `<Select/ >` component, documenting each of the component props
> Add `<Select />` component and its code

- src/design-system/data/Avatar/code/index.tsx
- src/design-system/data/Icon/code/index.tsx
- src/design-system/inputs/Button/code/index.tsx
- src/design-system/inputs/Label/code/index.tsx
- src/design-system/inputs/Select/code/index.tsx
- src/design-system/inputs/Switch/index.tsx
- src/design-system/inputs/Textarea/code/index.tsx
- src/design-system/inputs/Textfield/code/index.tsx
- src/pages/components/data/avatar/index.tsx
- src/pages/components/data/icon/index.tsx
- src/pages/components/inputs/Button/index.tsx
- src/pages/components/inputs/Label/index.tsx
- src/pages/components/inputs/Select/index.tsx
- src/pages/components/inputs/Switch/index.tsx
- src/pages/components/inputs/Textarea/index.tsx
- src/pages/components/inputs/Textfield/index.tsx
- src/pages/home/home.tsx
- src/routes/informationComponent.tsx
- tsconfig.json
- vite.config.ts
configure import aliases, allowing for greater readability and organization
> Add path aliases and update import statements

- src/design-system/data/Icon/code/parameters.ts
- src/design-system/data/Table/code/index.tsx
- src/design-system/data/Table/code/parameters.ts
- src/pages/components/data/Table/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Table />` component, where the props of the component are documented.
> Add `<Table />` component and its code

- src/design-system/data/Tag/code/index.tsx
- src/design-system/data/Tag/code/parameters.ts
- src/pages/components/data/Tag/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Tag />` component, where the component props are documented.
> Add `<Tag />` component and its code

- src/design-system/data/User/code/index.tsx
- src/design-system/data/User/code/parameters.ts
- src/pages/components/data/User/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<User />` component, where the component props are documented.
> Add `<User />` component and its code

- src/design-system/data/Icon/code/parameters.ts
- src/design-system/feedback/Assisted/code/index.tsx
- src/design-system/feedback/Assisted/code/parameters.ts
- src/pages/components/feedback/Assisted/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Assisted />` component, where the component's props are documented.
> Add content to code tabs for `<Assisted />`

- src/design-system/feedback/CountdownBar/code/index.tsx
- src/design-system/feedback/CountdownBar/code/parameters.ts
- src/pages/components/feedback/CountdownBar/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<CountdownBar />` component, where the component's props are documented.
> Add `<CountdownBar />` component and related files

- src/pages/home/home.tsx
display current section information, making navigation clearer
> Show current section information in `<Home /> page` 

- src/design-system/feedback/Spinner/code/index.tsx
- src/design-system/feedback/Spinner/code/parameters.ts
- src/pages/components/feedback/Spinner/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Spinner />` component, where the component's props are documented.
> Add content to code tabs for `<Spinner />`

- src/design-system/feedback/SectionMessage/code/index.tsx
- src/design-system/feedback/SectionMessage/code/parameters.ts
- src/pages/components/feedback/SectionMessage/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Table />` component, where the component's props are documented.
> add `<SectionMessage />`component and its code

- src/design-system/feedback/SkeletonIcon/code/index.tsx
- src/design-system/feedback/SkeletonIcon/code/parameters.tsx
- src/pages/components/feedback/SkeletonIcon/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Table />` component, where the component's props are documented.
> Add `<SkeletonIcon />` component and its code

- src/design-system/feedback/SkeletonLine/code/index.tsx
- src/design-system/feedback/SkeletonLine/code/parameters.ts
- src/pages/components/feedback/SkeletonLine/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<SkeletonLine />` component, where the component's props are documented.
> Add `<SkeletonLine />` component and its code

- src/design-system/navigation/Breadcrumbs/code/index.tsx
- src/design-system/navigation/Breadcrumbs/code/parameters.ts
- src/pages/components/navigation/Breadcrumbs/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Breadcrumbs />` component, where the component's props are documented.
> Add `<Breadcrumbs />` component and its code

- src/design-system/navigation/FullscreenNav/code/index.tsx
- src/design-system/navigation/FullscreenNav/code/parameters.tsx
- src/pages/components/navigation/FullscreenNav/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<FullscreenNav />` component, where the component's props are documented.
> Add `<FullscreenNav />` component and its code

- src/design-system/navigation/Header/code/index.tsx
- src/design-system/navigation/Header/code/parameters.tsx
- src/pages/components/navigation/Header/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Header />` component, where the component's props are documented.
> Add `<Header />` component and its code

- src/design-system/navigation/Nav/code/idex.tsx
- src/design-system/navigation/Nav/code/parameters.tsx
- src/pages/components/navigation/Nav/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Table />` component, where the component's props are documented.
> Add `<Nav />` component and its code

- src/design-system/navigation/Tabs/code/index.tsx
- src/design-system/navigation/Tabs/code/parameters.tsx
- src/pages/components/navigation/Tabs/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Tabs />` component, where the component's props are documented.
> Add `<Tabs />` component and its code

- src/design-system/utils/Blnaket/code/index.tsx
- src/design-system/utils/Blnaket/code/parameters.ts
- src/pages/components/utils/Blanket/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Blanket />` component, where the component's props are documented.
> Add Blanket component and its code

- src/design-system/data/Text/code/index.tsx
- src/design-system/data/Text/code/parameters.ts
- src/pages/components/data/Text/index.tsx
- src/pages/home/config/apps.config.tsx
- src/routes/informationComponent.tsx
Add the code page for the `<Text />` component, where the component's props are documented.
> Add `<Text />` component and its code

- package-lock.json
- package.json
Installed `react-syntax-highlighter`, syntax highlighting library
> Add react-syntax-highlighter package

- src/design-system/data/Tag/Playground/data.ts
- src/design-system/data/Tag/Playground/index.tsx
- src/design-system/data/Tag/Playground/type.ts
- src/pages/components/data/Tag/index.tsx
The Playground is implemented, allowing interactivity between the controls and the component to be documented `<Tag />`.
> Add `<Tag />` Playground component

- src/design-system/data/Avatar/Playground/index.tsx
- src/design-system/data/User/Playground/data.ts
- src/design-system/data/User/Playground/index.tsx
- src/design-system/data/User/Playground/types.ts
- src/pages/components/data/User/index.tsx
The Playground is implemented, allowing interactivity between the controls and the component to be documented `<User />`.
> Add content to Playground tab for  `<User />`

- src/design-system/inputs/Button/Playground/data.ts
- src/design-system/inputs/Button/Playground/index.tsx
- src/design-system/inputs/Button/Playground/type.ts
- src/design-system/inputs/Textarea/Playground/types.ts
- src/pages/components/inputs/Button/index.tsx
Add the ### Playground with its props controls handling functionality, for the documentation of the `<Button />` component.
> Add Playground with its props controls in `<Button />`

- src/design-system/feedback/SkeletonIcon/Playground/data.ts
- src/design-system/feedback/SkeletonIcon/Playground/index.tsx
- src/design-system/feedback/SkeletonIcon/Playground/types.ts
- src/pages/components/feedback/SkeletonIcon/index.tsx
The Playground is implemented, allowing interactivity between the controls and the component to be documented `<SkeletonIcon  />`.
> Add content to Playground tab for `<SkeletonIcon  />`

- src/design-system/feedback/CountdownBar/Playground/ data.ts
- src/design-system/feedback/CountdownBar/Playground/index.tsx
- src/design-system/feedback/CountdownBar/Playground/type.ts
- src/pages/components/feedback/CountdownBar/index.tsx
The Playground is implemented, allowing interactivity between the controls and the component to be documented `<CountdownBar />`.
> Add `<CountdownBar />` Playground component

- src/design-system/feedback/SkeletonLine/Playground/data.ts
- src/design-system/feedback/SkeletonLine/Playground/index.tsx
- src/design-system/feedback/SkeletonLine/Playground/type.ts
- src/pages/components/feedback/SkeletonLine/index.tsx
The Playground is implemented, allowing interactivity between the controls and the component to be documented `<SkeletonLine />`.
> Add `<SkeletonLine />` Playground component

- src/design-system/inputs/Label/Playground/data.ts
- src/design-system/inputs/Label/Playground/index.tsx
- src/design-system/inputs/Label/Playground/types.ts
- src/pages/components/inputs/Label/index.tsx
The Playground is implemented, allowing interactivity between the controls and the component to be documented  `<Label />`.
> Add content to Playground tab for `<Label />`

- src/design-system/navigation/Tabs/Playground/data.ts
- src/design-system/navigation/Tabs/Playground/index.tsx
- src/design-system/navigation/Tabs/Playground/styles.ts
- src/design-system/navigation/Tabs/Playground/type.ts
- src/pages/components/navigation/Tabs/index.tsx
Implemented the playground for the `<Tabs />` component allowing interactivity with its props.
> Add PlaygroundTabs component 

- src/design-system/utils/Blnaket/Playground/data.ts
- src/design-system/utils/Blnaket/Playground/index.tsx
- src/design-system/utils/Blnaket/Playground/styles.ts
- src/design-system/utils/Blnaket/Playground/type.ts
- src/pages/components/utils/Blanket/index.tsx
Implemented the playground for the `<Blanket />` component allowing interactivity with its props.
> Aadd PlaygroundBlanket component to `<Blanket />` utils

- src/design-system/navigation/Header/Playground/data.ts
- src/design-system/navigation/Header/Playground/index.tsx
- src/design-system/navigation/Header/Playground/mouck.tsx
- src/design-system/navigation/Header/Playground/type.ts
- src/pages/components/navigation/Header/index.tsx
implement the **playground** of the `<Header />` component allowing interactivity in the component's documentation
> Add PlaygroundHeader component to `<Header />`

- package-lock.json
- package.json
- src/design-system/data/Icon/Playground/index.tsx
- src/design-system/data/Table/Playground/mucks.tsx
This pull request details the comprehensive integration of the `inubekit-icon` library into our application, alongside the systematic replacement of all existing `<Icon />` components with their counterparts from the newly adopted library. Aimed at streamlining icon management and ensuring visual consistency across the application, this update leverages the enhanced features and extensive icon set provided by `inubekit-icon`.
> Install inubekit-icon and replace all `<Icon />` components

- package-lock.json
- package.json
- src/components/data/DetailsSection/index.tsx
- src/pages/Root/index.tsx
This pull request highlights the strategic implementation of the inubekit-hooks library across our application, coupled with the systematic replacement of all existing custom hooks with their enhanced counterparts from inubekit-hooks. Aimed at leveraging state-of-the-art hook functionalities and ensuring code uniformity, this update significantly optimizes our application's performance and development efficiency.
> Install inubekit-hooks and replace all hooks

- src/content/data/Icon/index.ts
- src/content/data/Tag/index.ts
- src/content/feedback/Assisted/index.ts
- src/content/feedback/CountdownBar/index.ts
- src/content/feedback/SectionMessage/index.ts
- src/content/feedback/SkeletonIcon/index.ts
- src/content/feedback/SkeletonLine/index.ts
- src/content/feedback/Spinner/index.ts
- src/content/inputs/Button/index.ts
- src/content/inputs/Fieldset/index.ts
- src/content/inputs/Toggle/index.ts
- src/content/navigation/Breadcrumbs/index.ts
- src/content/navigation/FullscreenNav/index.ts
- src/content/navigation/Header/index.ts
- src/content/navigation/Link/index.ts
- src/content/navigation/Nav/index.ts
- src/content/navigation/NavLink/index.ts
- src/content/navigation/Tabs/index.ts
- src/content/utils/Blanket/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
- src/pages/Root/index.tsx
- src/pages/Root/styles.ts
update config files of all the components in order to include the tokens
> update config files of all the components in order to include the tokens

- src/content/data/Icon/index.ts
- src/content/data/Tag/index.ts
- src/content/data/Text/index.ts
- src/content/feedback/Assisted/index.ts
- src/content/feedback/CountdownBar/index.ts
- src/content/feedback/SectionMessage/index.ts
- src/content/feedback/SkeletonIcon/index.ts
- src/content/feedback/SkeletonLine/index.ts
- src/content/feedback/Spinner/index.ts
- src/content/inputs/Button/index.ts
- src/content/inputs/Fieldset/index.ts
- src/content/inputs/Label/index.ts
- src/content/inputs/Toggle/index.ts
- src/content/navigation/Breadcrumbs/index.ts
- src/content/navigation/FullscreenNav/index.ts
- src/content/navigation/Header/index.ts
- src/content/navigation/Link/index.ts
- src/content/navigation/Nav/index.ts
- src/content/navigation/NavLink/index.ts
- src/content/navigation/Tabs/index.ts
- src/content/tokens/buildTokenDescriptions/index.ts
- src/content/utils/Blanket/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
adjusment in order to include the types for buildTokenDescriptions
> adjusment in order to include the types for buildTokenDescriptions

- src/content/inputs/Datefield/Controller/Datefield.Controller.tsx
- src/content/inputs/Datefield/index.ts
- src/content/inputs/Select/Controller/Select.Controller.tsx
- src/content/inputs/Select/index.ts
- src/content/inputs/Textarea/Controller/Textarea.Controller.tsx
- src/content/inputs/Textarea/index.ts
- src/content/inputs/Textfield/Controller/Textfield.Controller.tsx
- src/content/inputs/Textfield/index.ts
- src/content/utils/Blanket/Controller/Blanket.Controller.Styles.tsx
- src/content/utils/Blanket/Controller/Blanket.Controller.tsx
- src/content/utils/Blanket/index.tsx
Update content-config for the components that uses input-tokens
> Update content-config for the components that uses input-tokens

- src/components/data/DynamicComponentControls/index.tsx
- src/components/data/DynamicComponentControls/styles.ts
- src/components/data/DynamicComponentControls/util.tsx
- src/components/data/Table/styles.ts
- src/pages/Components/DynamicComponent/Tabs/IssuesAndSuggestions/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Playground/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Playground/styles.ts
- src/pages/Components/DynamicComponent/Tabs/PropsAndTypes/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
- src/pages/Components/DynamicComponent/index.tsx
This pull request updates the code to verify and adapt the gap size in accordance with the Figma documentation. By ensuring that the gap sizes are consistent with the design specifications, we maintain design integrity and improve the overall user interface.
> Verify the size of the gap to adapt according to the Figma documentation

- src/components/data/DynamicComponentControls/styles.ts
- src/components/data/DynamicComponentControls/util.tsx
This PR reviews and adjusts the behavior of the select component to align with the specifications outlined in the Figma documentation.
> Adjust Select Component Behavior According to Figma Documentation

- src/pages/Components/DynamicComponent/Tabs/Playground/index.tsx
This PR verifies and adjusts the padding of the fieldset component to ensure it aligns with the specifications outlined in the Figma documentation.
> Verify proper fieldset padding according to Figma documentation.

- package-lock.json
- package.json
- src/components/data/DynamicComponentControls/styles.ts
This pull request updates the dependencies to incorporate the latest version of the `<Select/>` component. Additionally, it removes customized and unnecessary styles to streamline the codebase and ensure better maintainability.
> Update dependencies in order to use the latest version of `<Select/>` and remove the customized and unnecessary styles

- src/content/inputs/Label/Controller/Label.Controller.tsx
- src/content/navigation/Link/Controller/Link.Controller.tsx
- src/content/navigation/Link/index.ts
- src/pages/Components/DynamicComponent/Tabs/Playground/styles.ts
This PR adjusts the size of the fieldset component to align with the guidelines provided in the documentation. The changes ensure consistency and improve the overall user experience by adhering to the recommended design specifications
> Adjust the fieldset size according to the documentation

- src/content/data/Avatar/index.ts
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/styles.ts
This pull request updates the theming section to align with the latest documentation. The changes ensure that the theming implementation is consistent with the documented guidelines.
> Update the theming section according to the documentation

- package-lock.json
- package.json
This pull request addresses the issue where the component loses its background shading when selected in the navigation. This update ensures that the selected component retains its background shading for better visual consistency and user experience.
> When the component is selected in the Nav it loses the background shading

- package-lock.json
- package.json
- src/content/index.ts
- src/content/layout/Divider/Controller/Divider.Controller.tsx
- src/content/layout/Divider/Controller/styles.ts
- src/content/layout/Divider/index.ts
- src/pages/Root/navigation.tsx
This PR includes the addition of the `<Divider />` component to the project and provides comprehensive documentation for its usage.
> Include and Document `<Divider />` Component

- src/components/data/Table/interface.tsx
- src/components/data/Table/styles.ts
This pull request aims to review and adapt the proportions of the table component to align with the specifications outlined in the Figma documentation.
> Check and Adapt Table Proportions According to Figma Documentation

- src/components/data/Table/styles.ts
This pull request aims to review and adapt the proportions of the table component to align with the specifications outlined in the Figma documentation.
> Check the proportions of the table to adapt according to the Figma documentation

- package-lock.json
- package.json
- src/pages/Root/index.tsx
- src/pages/Root/styles.ts
This PR updates the project dependencies to ensure compatibility with the latest version of the `<Nav/>` component. Keeping our dependencies up-to-date is crucial for maintaining security, performance, and access to new features.
>  Update Dependencies to Support Latest Version of `<Nav/>` Component

- src/pages/Components/DynamicComponent/Tabs/IssuesAndSuggestions/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Playground/styles.ts
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
- src/pages/Components/DynamicComponent/index.tsx
This pull request updates the font weights for layout titles and subtitles to improve visual hierarchy and readability.
> Update weights for layout titles and subtitles

- src/pages/Root/styles.ts
Update the padding that "main" receives, this should be 64px on all sides
> Modify the padding that "main" receives

- src/pages/Components/DynamicComponent/Tabs/IssuesAndSuggestions/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
This pull request addresses the adjustment of gaps for various pages, specifically focusing on theming and the IssuesAndSuggestions component.
> adjusment the gaps for pages(theming and IssuesAndSuggestions)

- src/components/data/DynamicComponentControls/styles.ts
- src/components/data/Table/styles.ts
This pull request addresses the positioning issues of the `<Select />` component, ensuring that the dropdown menu behaves consistently and predictably within the table layout.
> Fix Positioning Issues of `<Select />` Component

- src/content/data/Tag/Controller/Tag.Controller.tsx
- src/content/data/Tag/index.ts
- src/pages/Components/DynamicComponent/Tabs/IssuesAndSuggestions/index.tsx
This pull request reviews and fixes the implementation of the `<Tag />` component, addressing the erratic behavior currently observed.
> Review and Fix Implementation of `<Tag />` Component

- src/content/feedback/SkeletonIcon/index.ts
- src/content/feedback/SkeletonLine/index.ts
- src/content/index.ts
- src/pages/Components/DynamicComponent/index.tsx
This pull request updates the content configuration to ensure the correct command is used for installation. This change will streamline the installation process and avoid potential issues caused by incorrect commands.
> Update Content Configuration to Use the Correct Command for Installation

- package.json
This pull request updates various dependencies to ensure our project uses the latest version of the `<Select/>` component. This will bring new features, improvements, and security updates to our selection functionality.
> Update Dependencies to Use the Latest Version of `<Select/>`

- src/pages/Components/DynamicComponent/Tabs/PropsAndTypes/index.tsx
- src/pages/Components/DynamicComponent/Tabs/PropsAndTypes/styles.ts
This pull request addresses the overflow issues on grid elements within the new accordion component. Ensuring that grid elements are displayed correctly within the accordion will enhance the user experience and visual consistency.
> Check Overflow on Grid Elements in the New Accordion Component

- src/content/data/Avatar/index.tsx
- src/content/data/Icon/index.tsx
- src/content/data/Tag/index.tsx
- src/content/data/Text/index.tsx
- src/content/data/User/index.tsx
- src/content/feedback/Assisted/index.tsx
- src/content/feedback/CountdownBar/index.tsx
- src/content/feedback/SectionMessage/index.tsx
- src/content/feedback/SkeletonIcon/index.tsx
- src/content/feedback/SkeletonLine/index.tsx
- src/content/feedback/Spinner/index.tsx
- src/content/inputs/Button/index.tsx
- src/content/inputs/Datefield/index.tsx
- src/content/inputs/Fieldset/index.tsx
- src/content/inputs/Label/index.tsx
- src/content/inputs/Select/index.tsx
- src/content/inputs/Textarea/index.tsx
- src/content/inputs/Textfield/index.tsx
- src/content/inputs/Toggle/index.tsx
- src/content/layout/Divider/index.tsx
- src/content/layout/Grid/index.tsx
- src/content/layout/Stack/index.tsx
- src/content/navigation/Breadcrumbs/index.tsx
- src/content/navigation/FullscreenNav/index.tsx
- src/content/navigation/Header/index.tsx
- src/content/navigation/Link/index.tsx
- src/content/navigation/Nav/index.tsx
- src/content/navigation/Tabs/index.tsx
- src/content/utils/Blanket/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Playground/index.tsx
This PR updates the Playground component to optimize the loading of frames from CodeSandbox by prefetching the iframe content. This ensures that the iframe content is rendered immediately when the component is displayed, providing a faster and smoother loading experience.
> Update Playground Component to Use Prefetched CodeSandbox Frames

- src/pages/Components/DynamicComponent/Tabs/Playground/index.tsx
- src/pages/Components/DynamicComponent/index.tsx
- src/pages/Components/DynamicComponent/styles.ts
This PR adjusts the titles and sizes throughout the application to align with the specifications outlined in the Figma designs. These changes ensure visual consistency and adherence to the design guidelines provided. Please review the updates to confirm they match the expected design standards.
> Adjust titles and sizes in order to follow figma designs

- package-lock.json
- package.json
- src/components/data/Table/Pagination/styles.tsx
- src/components/data/Table/interface.tsx
- src/components/data/Table/styles.ts
- src/pages/Components/DynamicComponent/Tabs/Playground/index.tsx
- src/pages/Components/DynamicComponent/Tabs/PropsAndTypes/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/index.tsx
- src/pages/Components/DynamicComponent/Tabs/Theming/styles.ts
- src/pages/Components/DynamicComponent/Tabs/utils/getTokenNameFromValue.ts
- src/pages/Components/DynamicComponent/index.tsx
- src/pages/Root/index.tsx
This pull request focuses on cleaning up the Theming component by removing unnecessary and unused code.
> Remove Unnecessary and Unused Code from Theming Component

- src/content/inputs/Button/index.tsx
- src/pages/Components/DynamicComponent/Tabs/PropsAndTypes/index.tsx
This PR introduces detail modals for the `<Button />` component, enhancing the user experience by providing detailed information and interaction options related to buttons within the application.
> Create `<Button />` Detail Modals

- src/content/data/Text/index.tsx
Update documentation content that appears on detail modal
>  Add `<Text />` detail modals

- src/content/inputs/Fieldset/index.tsx
- src/content/inputs/Label/index.tsx
- src/content/inputs/Toggle/index.tsx
- src/content/layout/Stack/index.tsx
- src/content/layout/StackItem/Controller/Stack.Controller.styles.ts
- src/content/layout/StackItem/Controller/Stack.Controller.tsx
- src/content/layout/StackItem/index.tsx
This pull request introduces detail modals to the application, enhancing the user experience by providing additional information in a pop-up format.
> Added Detail Modals to Application

- src/content/data/Avatar/index.tsx
- src/content/data/Icon/index.tsx
- src/content/data/Table/index.tsx
- src/content/data/Tag/index.tsx
- src/content/data/User/index.tsx
- src/content/feedback/Assisted/index.tsx
- src/content/inputs/Datefield/index.tsx
- src/content/inputs/Select/index.tsx
- src/content/inputs/Textfield/index.tsx
This pull request introduces detail modals to the application, enhancing the user experience by providing additional information in a pop-up format
> Update Detail Modals to Application

- src/content/feedback/CountdownBar/index.tsx
- src/content/feedback/Flag/index.tsx
- src/content/feedback/SkeletonIcon/index.tsx
- src/content/feedback/Spinner/index.tsx
This pull request introduces detail modals to the application, enhancing the user experience by providing additional information in a pop-up format.
> Update documentation for feedback-components in content

- package-lock.json
- package.json
- src/content/index.ts
- src/content/navigation/Menu/index.tsx
- src/pages/Root/navigation.tsx
This pull request introduces detailed modals for the `<Menu />` component. These modals are designed to provide users with additional information and options within the menu interface. Each modal is tailored to specific details relevant to the selected menu item, enhancing the overall user experience.
> Create `<Menu />` Detail Modals
